apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
      nodePort: 31450